Some suggestions on DPM refactoring
futurewei-cloud/alcor pull request #377
Opened 2020-09-07 10:45 UTC by chenpiaoping

I am thinking about DPM supporting pulsar, in order to make DPM support multiple message queues, I think it is necessary to ReFactor the code of DPM.

2020-09-07 10:48 UTC, chenpiaoping commented
@xieus @haboy52581 I have a few more questions about the structure of NetworkConfiguration:
1. What information should be included in NetworkConfiguration when only security groups are updated.
2. What information should be included in NetworkConfiguration when only router information are updated.

2020-09-08 03:14 UTC, xieus commented
> @xieus @haboy52581 I have a few more questions about the structure of NetworkConfiguration:
> 
> 1. What information should be included in NetworkConfiguration when only security groups are updated.
> 2. What information should be included in NetworkConfiguration when only router information are updated.

We should have a new API in DPM that support SG and router (including update of routing table and rules). The method of the API is either PATCH or PUT, and the NetworkConfiguration object includes the port that requires information update, and a list of SGs or Routers to be updated. 

DPM should convert the PM message to protobuf message, with 
- the operation type of port as INFO 
- the operation type of SGs or Routers as UPDATE

2020-09-08 03:20 UTC, xieus commented
> I am thinking about DPM supporting pulsar, in order to make DPM support multiple message queues, I think it is necessary to Refactor the code of DPM.

Thanks @chenpiaoping Sounds good to me. At first glance, the PR added a few items that have been long overdue. I will look further with more comments.

2020-09-10 04:08 UTC, xieus approved these changes
Completed review of entity classes change and left a few minor comments.

2020-09-10 04:08 UTC, xieus commented on web/src/main/java/com/futurewei/alcor/web/entity/router/RouterSubnetUpdateInfo.java
> +public class RouterSubnetUpdateInfo {
Not quite sure what this class is about. Could you add some comments to the beginning of this class?

2020-09-10 04:24 UTC, xieus commented on services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
> +        for (NodeInfo nodeInfo: nodeInfos) {
What if nodeInfos=NULL?

2020-09-10 04:24 UTC, xieus commented on services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
> +        List<NeighborInfo> neighborInfos = context.getNetworkConfig().getNeighborInfos();
Does this neighborInfos only contain L2 neighbor at this time?

2020-09-10 04:24 UTC, xieus commented on services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
> +        for (NeighborInfo neighborInfo: neighborInfos) {
What if neighborInfos=NULL?

2020-09-10 04:24 UTC, xieus commented on services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
> +            if (neighborInfo.getPortId().equals(fixedIp.getIpAddress())) {
Is it neighborInfo.getPortIp()?

2020-09-10 04:24 UTC, xieus commented on services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
> +                buildL3Neighbors(context, internalPortEntity, fixedIp, routerSubnetIds);
how frequently do we go into this block to trigger buildL3Neighbors? This could be a N^2 operation.

2020-09-10 04:34 UTC, xieus reviewed
Completed review of PM change. Will continue to review DPM change...

2020-09-10 04:34 UTC, xieus commented on services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/RouterProcessor.java
> +    }
Looks a bit strange. Maybe these methods are not yet implemented?

2020-09-10 04:34 UTC, xieus commented on services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
> +        return null;
throw UnsupportedOperationException exception.

2020-09-10 04:46 UTC, xieus requested changes

2020-09-10 04:46 UTC, xieus commented on services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
> +
throw UnsupportedOperationException for all similar methods to remind ourselves..

2020-09-10 04:46 UTC, xieus commented on services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/UnicastGoalState.java
> +    private String nextTopic;
is nextTopic or currentTopic :-)

2020-09-10 04:46 UTC, xieus commented on services/data_plane_manager/src/main/resources/application.properties
> +host.ip.to.group.topic.map=group-topic1:10.10.10.10,10.10.10.11 group-topic2:11.11.11.11,11.11.11.12
This has the potential to become one of the largest configurations :-) 

Put it here is fine as of now but we might need to think of a different way to store it.

2020-09-10 04:48 UTC, xieus commented
@chenpiaoping Please check https://jenkins.alkaidcloud.io/job/alcor-controller-pr-test/990/console to find some compile error for DPM.

2020-10-19 21:33 UTC, xieus commented
@chenpiaoping I knew that you've checked in a portion of this PR to master in PR https://github.com/futurewei-cloud/alcor/pull/366. Do you have some remaining files to be checked in? If so, please rebase from master; otherwise we can close this PR. Let me know.

2020-10-20 01:56 UTC, chenpiaoping commented
> @chenpiaoping I knew that you've checked in a portion of this PR to master in PR #366. Do you have some remaining files to be checked in? If so, please rebase from master; otherwise we can close this PR. Let me know.

No, please close it.

2020-10-20 02:23 UTC, xieus commented
Part of the PR has been merged to master in #366 . Close this PR as it becomes outdated.

2020-10-20 02:23 UTC, closed without merging