Jaeger Integration client for vpc and route
futurewei-cloud/alcor pull request #516
Opened 2020-12-16 21:51 UTC by haboy52581

2020-12-17 00:03 UTC, xieus reviewed
Some early comments.

2020-12-17 02:59 UTC, cj-chung commented
We can try to use OpenTracing Instrumentation in our code, it seems easier to integrate OpenTracing Instrumentation with Java Spring Boot Microservices. Both Jaeger and Zipkin are able to collect OpenTracing's trace info. 
https://github.com/opentracing-contrib/java-spring-jaeger
https://www.hawkular.org/blog/2017/06/9/opentracing-spring-boot.html

2020-12-18 00:47 UTC, haboy52581 commented
per discussion with team, the opentracing way for now is not workable in this PR and we would explore more in separate PR

2020-12-18 03:07 UTC, xieus commented
@haboy52581 Please address the comments made yesterday in the PR and in the afternoon daily sync-up. Also, please check the CI failure.

2020-12-18 03:08 UTC, xieus commented
> @haboy52581 Please address the comments made yesterday in the PR and in the afternoon daily sync-up. Also, please check the CI failure.

On top of current comments, I will continue to review and likely make a few more comments.

2020-12-24 19:10 UTC, haboy52581 commented on lib/src/main/java/com/futurewei/alcor/common/config/JaegerConfig.java
> +    public String jaegerMaxQsize;
changed in 8ef79aa

2020-12-28 18:35 UTC, xieus commented
CI reports API GW launch issue: https://jenkins.alkaidcloud.io/job/alcor-controller-pr-test/1299/console

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vpcRouteLocator' defined in class path resource [com/futurewei/alcor/apigateway/route/VpcRouteConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.gateway.route.RouteLocator]: Factory method 'vpcRouteLocator' threw exception; nested exception is java.lang.NullPointerException
```

2020-12-28 18:42 UTC, xieus reviewed
> @xieus @haboy52581
> We can try to use OpenTracing Instrumentation in our code, it seems easier to integrate OpenTracing Instrumentation with Java Spring Boot Microservices. Both Jaeger and Zipkin are able to collect OpenTracing's trace info.
> [opentracing-contrib/java-spring-jaeger](https://github.com/opentracing-contrib/java-spring-jaeger)
> [hawkular.org/blog/2017/06/9/opentracing-spring-boot.html](https://www.hawkular.org/blog/2017/06/9/opentracing-spring-boot.html)
> [opentracing-contrib/java-spring-web](https://github.com/opentracing-contrib/java-spring-web)

Thanks. Let us try this. @haboy52581

2020-12-28 18:42 UTC, xieus commented on lib/pom.xml
> +            <groupId>io.zipkin.brave</groupId>
If our solution is built atop Jaeger, io.zipkin.brave should not be our dependency. 

Check https://github.com/openzipkin/brave, brave is a distributed tracing instrumentation library. 

Please try to remove io.zipkin.brave.

2020-12-29 18:32 UTC, xieus requested changes
We should resolve test failure, instead of commenting UTs to make CI happy.

2020-12-29 18:32 UTC, xieus commented on services/api_gateway/pom.xml
> +            <groupId>io.zipkin.brave</groupId>
There is another Zipkin dependency.

2020-12-29 18:32 UTC, xieus commented on services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/AlcorApiGatewayApplicationTest.java
> +//    private KeystoneClient keystoneClient;
Why do we comment the entire test case?

2020-12-29 18:32 UTC, xieus commented on services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/KeystoneAuthWebFilterTest.java
> +//    }
Please don't comment out UTs.

2020-12-29 18:32 UTC, xieus commented on services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/KeystoneClientTest.java
> +//})
Please uncomment UTs.

2020-12-30 18:59 UTC, haboy52581 commented on services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/KeystoneAuthWebFilterTest.java
> +//    }
uncommented

2020-12-30 18:59 UTC, haboy52581 commented on services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/KeystoneClientTest.java
> +//})
uncommented

2020-12-30 18:59 UTC, haboy52581 commented on services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/AlcorApiGatewayApplicationTest.java
> +//    private KeystoneClient keystoneClient;
uncommented

2020-12-30 18:59 UTC, haboy52581 commented on services/api_gateway/pom.xml
> +            <groupId>io.zipkin.brave</groupId>
removed

2020-12-30 19:01 UTC, haboy52581 commented on lib/pom.xml
> +            <groupId>io.zipkin.brave</groupId>
removed

2021-01-06 00:10 UTC, haboy52581 commented
Per discussion with team I would hold on to this PR since PR 531 https://github.com/futurewei-cloud/alcor/issues/531 we would work into and probably go with open tracing or neither way on the Alcor project per discussion with Liguang/James/Eric

2021-01-06 00:11 UTC, haboy52581 commented on lib/pom.xml
> +            <groupId>io.zipkin.brave</groupId>
removed

2021-01-06 00:12 UTC, haboy52581 commented on services/api_gateway/pom.xml
> +            <groupId>io.zipkin.brave</groupId>
removed

2021-01-06 00:13 UTC, haboy52581 commented on services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/AlcorApiGatewayApplicationTest.java
> +//    private KeystoneClient keystoneClient;
reverted

2021-01-06 00:13 UTC, haboy52581 commented on services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/KeystoneClientTest.java
> +//})
reverted

2021-01-06 00:13 UTC, haboy52581 commented on services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/KeystoneAuthWebFilterTest.java
> +//    }
reverted

2021-07-01 17:33 UTC, xieus commented
The issue to be addressed by this PR has been addressed by a new PR #651 therefore we close this PR.

2021-07-01 17:33 UTC, closed without merging